language: php

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.6
      dist: trusty
    - php: 7.0
      dist: trusty

script: phpunit
